### ISSUE TITLE
fix: 모집연장 관련 비즈니스 로직 수정

### ISSUE THREAD

**Issue by dl-00-e8** [Gongjakso/server#103]
## 💼 IssueName
모집연장 관련 비즈니스 로직 수정

## 📝 Description
기존 모집 연장 요청 시, 모집 연장 날짜만 변경되는 구조였으나 현재 모집 연장 상태에 대해서 프론트에서 별도로 확인이 필요하다는 것을 확인했음
그렇기에, 공고 상태 칼럼에서 모집 연장과 관련된 정보를 새로 추가하는 것과 더불여 신청쪽에서도 이를 연관시켜서 관리하여야 함.

## ❗️ Todo
- [x] 공고 상태 관리 ENUM 최신화
- [x] 모집 연장 API 비즌니스 로직 수정
- [x] 신청 API 중 모집 연장 로직에 영향받은 API 수정
