### ISSUE TITLE
feat: 신청 취소 시 공고 게시자에게 이메일 전송 로직 추가

### ISSUE THREAD

**Issue by dl-00-e8** [Gongjakso/server#115]
## 💼 IssueName
신청 취소 시 공고 게시자에게 이메일 전송 로직 추가

## 📝 Description
신청 취소 이후, 팀장이 웹 서비스에 접속하였을 때, 신청 취소된 목록을 보고자 함.

## ❗️ Todo
- [x] 지원 취소 API 개발
- [x] 이메일 전송 서드파티 선정
- [x] 이메일 전송 Component 추가
- [ ] 이메일 발송 템플릿 구축
- [ ] 신청취소 시, 이메일 발송되도록 연결
