### ISSUE TITLE
fix: Team DTO 변경 및 Enum 추가, 일부 비즈니스 로직 업데이트

### ISSUE THREAD

**Issue by dl-00-e8** [Gongjakso/server#210]
## 💼 IssueName
> 이슈 명을 작성해주세요.

Team DTO 변경 및 Enum 추가, 일부 비즈니스 로직 업데이트

## 📝 Description
> 이슈에 대해 간결하게 설명해주세요.

- Team DTO의 팀장 변수명을 leaderName으로 수정
- 사용자가 지원한 역할에 대한 변수 추가
- teamStatus에서 활동 중/활동 종료 변수 추가

## ❗️ Todo
- [x] Team DTO의 팀장 변수명을 leaderName으로 수정
- [x] 사용자가 지원한 역할에 대한 변수 추가
- [x] teamStatus에서 활동 중/활동 종료 변수 추가
