### ISSUE TITLE
fix: 내가 지원한/모집 중인 팀 API 업데이트

### ISSUE THREAD

**Issue by dl-00-e8** [Gongjakso/server#216]
## 💼 IssueName
> 이슈 명을 작성해주세요.

내가 지원한/모집 중인 팀 API 업데이트

## 📝 Description
> 이슈에 대해 간결하게 설명해주세요.

- 내가 지원한 팀에서는 사용자가 지원한 역할만 반환
- 내가 모집중인 팀에서는 모집하는 모든 파트를 반환
- 팀 응답은 모든 파트를 반환

## ❗️ Todo
- [ ] 내가 지원한 팀에서는 사용자가 지원한 역할만 반환
- [x] 내가 모집중인 팀에서는 모집하는 모든 파트를 반환
- [x] 팀 응답은 모든 파트를 반환
