### ISSUE TITLE
fix: 포트폴리오 및 지원 관련 코드 수정

### ISSUE THREAD

**Issue by yumzen** [Gongjakso/server#249]
## 💼 IssueName
> 포트폴리오 및 지원 관련 코드 수정

## 📝 Description
> 이슈에 대해 간결하게 설명해주세요.

## ❗️ Todo
- [x] 포트폴리오 열람 권한 수정
- [x] 지원 조회 시 반환 데이터 추가
- [x] 응답 데이터 통일
