### ISSUE TITLE
test: banner unit test code 작성

### ISSUE THREAD

**Issue by dl-00-e8** [Gongjakso/server#41]
## 💼 IssueName
Banner 도메인 Unit test code 작성

## 📝 Description
Banner 도메인 관련 Unit test code 작성 (메인 페이지, 프로젝트 페이지, 공모전 페이지)

## ❗️ Todo
- [ ] Banner 미리 만드는 Util 파일 생성
- [ ] 메인 페이지 Unit test
- [ ] 프로젝트 페이지 Unit test
- [ ] 공모전 페이지 Unit test
