### ISSUE TITLE
chore: AWS 운영 서버 배포

### ISSUE THREAD

**Issue by dl-00-e8** [Gongjakso/server#7]
## 💼 IssueName
AWS 운영 서버 배포

## 📝 Description
AWS 운영 서버 배포 및 정상 연결 확인

## ❗️ Todo
- [ ] AWS 운영 서버 설계
- [ ] AWS 설계 기반 서버 배포
- [ ] 배포 자동화 파이프라인 구축
