### ISSUE TITLE
feat: 공고 조회 관련 추가 API 개발

### ISSUE THREAD

**Issue by dl-00-e8** [Gongjakso/server#98]
## 💼 IssueName
공고 조회 관련 추가 API 개발

## 📝 Description
특정 공고 조회하는 페이지 접근 시, 팀장/팀원 여부에 따라서 렌더링되는 뷰가 달라지므로 이를 조건 분기하기 위한 팀장/팀원 구분 API 및 추가 API 개발

## ❗️ Todo
- [ ] 변경된 User Flow 정의
- [ ] API 명세서 정의
- [ ] 팀장/팀원 확인하는 API 개발
- [ ] 일반 사용자와 팀장/팀원인 경우 요청되는 API 구분 개발
